import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.scss'
import Header from "../components/header/Header";
import ServiceIcon from "../components/index/ServiceIcon";

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Y Search Skin</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <Header/>
        {/*<div className={styles.location}>*/}
        {/*  <svg className="geolink__button" xmlns="http://www.w3.org/2000/svg" width="16" height="16"*/}
        {/*       viewBox="0 0 16 16">*/}
        {/*    <path fill="currentColor"*/}
        {/*          d="M13.07 3.58l-4 9.98a.5.5 0 0 1-.95-.06L7 9 2.5 7.88a.5.5 0 0 1-.06-.95l9.98-4a.5.5 0 0 1 .65.65z"></path>*/}
        {/*  </svg>*/}
        {/*  Москва 16 ноября 19:36*/}
        {/*</div>*/}
        <div style={{
          display: 'grid',
          gridAutoFlow: 'column',
          // gridTemplateColumns: 'auto auto auto auto auto auto auto auto',
          gridColumnGap: 60,
          marginBottom: 24,
          marginTop: 25
        }}>
          <ServiceIcon />
          <ServiceIcon />
          <ServiceIcon />
          <ServiceIcon />
          <ServiceIcon />
          <ServiceIcon />
          <ServiceIcon />
          <ServiceIcon />
        </div>
        <h1 className={styles.title}>
          Welcome to <a href="https://nextjs.org">Next.js!</a>
        </h1>

        <p className={styles.description}>
          Get started by editing{' '}
          <code className={styles.code}>pages/index.js</code>
        </p>

        <div className={styles.grid}>
          <a href="https://nextjs.org/docs" className={styles.card}>
            <h2>Documentation &rarr;</h2>
            <p>Find in-depth information about Next.js features and API.</p>
          </a>

          <a href="https://nextjs.org/learn" className={styles.card}>
            <h2>Learn &rarr;</h2>
            <p>Learn about Next.js in an interactive course with quizzes!</p>
          </a>

          <a
            href="https://github.com/vercel/next.js/tree/master/examples"
            className={styles.card}
          >
            <h2>Examples &rarr;</h2>
            <p>Discover and deploy boilerplate example Next.js projects.</p>
          </a>

          {/*<a*/}
          {/*  href="https://vercel.com/new?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"*/}
          {/*  className={styles.card}*/}
          {/*>*/}
          {/*  <h2>Deploy &rarr;</h2>*/}
          {/*  <p>*/}
          {/*    Instantly deploy your Next.js site to a public URL with Vercel.*/}
          {/*  </p>*/}
          {/*</a>*/}
        </div>
      </main>

      <footer className={styles.footer}>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by{' '}
          <span className={styles.logo}>
            <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
          </span>
        </a>
      </footer>
    </div>
  )
}
